# Generated by Django 4.1.6 on 2023-03-12 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=4)),
                ('placa_tipo', models.CharField(choices=[('mercosul', 'Mercosul'), ('modelo antigo', 'Modelo antigo')], max_length=13)),
                ('placa', models.CharField(max_length=8, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('endereço', models.CharField(max_length=100)),
                ('número', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peça',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_peça', models.CharField(max_length=255)),
                ('produto', models.CharField(max_length=255)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('código', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviço', models.CharField(max_length=255)),
                ('descrição', models.TextField()),
                ('status', models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7)),
                ('valor_serviço', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='adm.carro')),
                ('pecas', models.ManyToManyField(related_name='servicos', to='adm.peça')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='adm.cliente'),
        ),
    ]
