# Generated by Django 4.1.6 on 2023-02-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_alter_carro_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='placa_tipo',
            field=models.CharField(choices=[('modelo antigo', 'Modelo antigo'), ('mercosul', 'Mercosul')], max_length=13),
        ),
    ]
