# Generated by Django 4.1.6 on 2023-02-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_alter_carro_placa_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carros', to='adm.cliente'),
        ),
    ]
