# Generated by Django 4.1.6 on 2023-03-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_alter_carro_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviço', models.CharField(max_length=255)),
                ('descrição', models.TextField()),
                ('status', models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7)),
                ('valor_serviço', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='adm.carro')),
            ],
        ),
    ]
